### ISSUE TITLE
Database is not updating (please reopen this issue if it happens again) 

### ISSUE THREAD

**Issue by sassbalint** [dlazesz/cfpdb#2]
I see that the daily update is not working currently. Please, check if possible.
https://dlazesz.github.io/cfpdb

**Comment by dlazesz** [comment]
Thank you. Fixed. There was a problem with the data which has remained unnoticed. I have installed a github action for instant updates which helps in earlier detection of such errors.

**Comment by sassbalint** [comment]
Thank you. <3

**Comment by sassbalint** [comment]
Thank you, it works now perfectly. :heart:
